### ISSUE TITLE
Missing file in chn-files.json

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus#134]
The following is not in the chn-files.json: X21n0389

**Comment by ayya-vimala** [comment]
It is in the lists on my backend:
![image](https://user-images.githubusercontent.com/49606945/90126046-4ce81380-dd63-11ea-9062-d5356c451ed3.png)

This is what I have after checking:
```
// Files mentioned in the lists but no json file found on server
[
"X04n0223",
]
// JSON files found on server but not mentioned in the lists 
[
"T31n1600-002",
"T31n1600-003",
]
```

**Comment by ayya-vimala** [comment]
So I will just push the lists I have instead and add X04n0223
You mentioned that the two files -002 and -003 can be ignored.
