### ISSUE TITLE
Text view Folio selection not being displayed as expected

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#236]
**updated spec:** per https://github.com/BuddhaNexus/buddhanexus/issues/236#issuecomment-2346901047

---

Original description: 

This might be a known issue but I didn't see an issue ticket for it so here it is:
Folio numbers are not working in text view mode.
When I select a folio number in the text-view mode it simply thinks for a bit and then goes to the top of the page.
Tested in pali and tibetan.

I tried in the docs but the backend gives back the same data regardless of the folio number used. So this needs to be changed in the backend.

**Comment by ayya-vimala** [comment]
The frontend text view gives `active_segment='none'` at all times. So the backend cannot know where to scroll to.

**Comment by aminahbl** [comment]
Hey @sebastian-nehrdich I've had a look at this, and although it's quite old now I'm wondering if there is still some kind of issue that needs to be addressed? I think something, indeed, might not be working correctly, but I don't know what the desired behaviour is. 

What I can confirm is that that the `folio` id **is** being sent to the backend:

![Image](https://github.com/user-attachments/assets/b427c1c3-c117-4939-9714-2cec0d89698a)

![Image](https://github.com/user-attachments/assets/319e1fa2-f8df-4fd5-9a64-014381b4e30a)

**Comment by ayya-vimala** [comment]
It's certainly not working yet and when I'm back next month I'll have a good look at what's happening.

**Comment by aminahbl** [comment]
Hey @ayya-vimala! Hope you're enjoying your adventures! :cowboy_hat_face: 

Yes, after adding my comment, we discussed this in the team meeting, noting that the handling needs to be figured out (including the difference in behaviour in different views).

**Comment by ayya-vimala** [comment]
Is this the same issue as #164?

**Comment by aminahbl** [comment]
Probably best to check with @TrebuhD on that one, but I think #164 was resolved.

**Comment by ayya-vimala** [comment]
OK. This one is not resolved in any case.

**Comment by aminahbl** [comment]
Cool, but the issue should probably be updated, because per above it looks like the data is being passed in the request. Do you want to double check in the network request?

**Comment by TrebuhD** [comment]
We determined that the dropdown should show the value of the `num` property and not `segment_nr` like it does now.

 ![Image](https://github.com/user-attachments/assets/8bc28a3c-1f65-4bf6-8e1f-aa832a001cac).

The FE should then pass this value to the BE (within the `https://dharmamitra.org/api-db/text-view/text-parallels-v2/` request), which would then return the text starting with that folio. In this case, the FE cannot pass the `active_segment` value - it should be cleared from the client URL when a folio is selected.

**Comment by ayya-vimala** [comment]
The folio numbers now display correctly in the dropdown.

What I get passed into the backend upon selecting a folio number is as follows:
`ALL INPUTS file_name='an10' active_segment='none' score=30 par_length=30 limits=Limits(category_include=[], category_exclude=[], file_include=[], file_exclude=[]) multi_lingual=['skt', 'pli', 'chn', 'tib'] page_number=0`

I get `active_segment='none'` which as I understood we agreed is correct, but I don't see a folio number being passed to the backend.

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich  - As the AQL query for this needs changing too to include the folio, I will not proceed until the backend is updated.

**Comment by ayya-vimala** [comment]
I had a look at the backend and you can add `FILTER segment.folio == @folio`to the query BUT that clashes with the page numbers. What happens if you ask for a page number (probably 0) when the folio is in a different page? So we should have something that either uses pages OR folios but not both.

**Comment by sebastian-nehrdich** [comment]
Looking into this problem closely for a couple of hours, the only sensible solution that I can suggest for text-view is: 
- implement another helper endpoint /utils/active-segment-for-folio/ with two parameters: filename and folio number; this endpoint will return an segment_nr that we can pass to the text-view as active_segment  
- after selecting a folio in text view, the frontend queries this new endpoint in order to get the segmentnr that it needs to pass as active_segment value to the text-view so that gets scrolled to the right position 
- the reason why we can't solve it all on the backend is that we also need to scroll the text-view into the right position, and that is already implemented via the active_segment handling. Let me know what you think!

**Comment by ayya-vimala** [comment]
It's not an elegant solution but is it possible to link the folio to an active segment? So if I want folio 2 for instance, make the active segment the first segment in folio 2?

Of course this creates a problem because the frontend doesn't know that what the active segment is supposed to be in that case.

So the only way to solve that is if the frontend knows the first segment of each folio and instead of asking the backend for folio 2, it asks for the active segment connected with folio 2.

Not sure if I'm making any sense here but it does away with the API  request for folio x altogether and the drop-down list for folio knows the active segment connected with it (without displaying it).

**Comment by sebastian-nehrdich** [comment]
On Fri, Dec 27, 2024 at 7:37 PM Ven. Vimala ***@***.***>
wrote:

> It's not an elegant solution but is it possible to link the folio to an
> active segment? So if I want folio 2 for instance, make the active segment
> the first segment in folio 2?
>

this is precisely what my suggested solution would be, give the active
segment for folio 2. The frontend needs to handle the scrolling here, so it
needs to know the active segment!

> Of course this creates a problem because the frontend doesn't know that
> what the active segment is supposed to be in that case.
>

see above, that’s why we ask the backend for that active segment for the
folio here.

> So the only way to solve that is if the frontend knows the first segment
> of each folio and instead of asking the backend for folio 2, it asks for
> the active segment connected with folio 2.
>

right.

Not sure if I'm making any sense here but it does away with the API request
> for folio x altogether and the drop-down list for folio knows the active
> segment connected with it (without displaying it).
>

the active segments can also be dumped directly into the menu, or queried
with the endpoint, will yield the same result…

**Comment by ayya-vimala** [comment]
I don't like the solution of having an extra query here that queries the backend on which active segment is the folio requested.

But like you say, maybe just putting the first segment of each folio in the drop-down instead. ..

But then we need to think about why we have folio numbers and what it does with the table and numbers view. For the table view it gives only those segments that have that folio in it, for the numbers view it starts with that folio but also displays those below ...
So all three have a different way of dealing with it. 

Maybe have a different drop-down for text view makes sense.

**Comment by sebastian-nehrdich** [comment]
I agree that its an ugly solution. but I looked at the code and I won't be able to rewrite the dataloader sufficiently to have the first segment in place. I can do the endpoint now, anything else will need more time.

**Comment by ayya-vimala** [comment]
I see. Yes, time is an issue.
If it's easier for you now, maybe do that and we can do something else later, maybe for DN.
