### ISSUE TITLE
Matches for some files are missing from DB

### ISSUE THREAD

**Issue by angirov** [BuddhaNexus/buddhanexus#250]
Ven: Vimala:
there are files where the parallels are not loaded. For instance dn4:  ... /db/pli/dn4/text
These parallels do exist but don't seem to be there. So it is with a lot of files I now checked.
I checked the database because I thought it was an API issue but the parallels are simply not there.

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala does this still apply?

**Comment by ayya-vimala** [comment]
This specific issue was about loading the data in into the Arango database which wasn't done correctly so no matches showed up for half of the files. This has been resolved. However, looking closer to the actual matches that are generated I do see some discrepancies where the old BN1 database performs a lot better. I'll make a separate issue for this.
