### ISSUE TITLE
Table view gives back items from other texts than the one selected

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#257]
Steps to reproduce:

1. Go to Pali -> DN3
2. Set to Table View
3. Set an include filter of Atthakatha Vinaya (just to reduce the number of matches to 20 so it's easy to see)
4. Scroll down past the first 20 matches of DN3, you can then see it goes into DN31, DN32, DN33, etc. giving all the matches of those as well.

The error is in the dataloader part of the backend. In Arango in collection  `parallels_sorted_file` for `_key == dn3` it gives also dn30, etc. So there is an error in a regex somewhere. Therefore it ends up with way too many items in list.

**Comment by sebastian-nehrdich** [comment]
I fixed this, please check if you still find such instances, otherwise we can close this.

**Comment by ayya-vimala** [comment]
This seems to work now. The only problem still is that at the bottom it keeps on showing the loading symbol as if there is more but that's a separate issue. I will close this one.

**Comment by sebastian-nehrdich** [comment]
I suspect that is a separate issue, not a backend one...
