### ISSUE TITLE
Refactor limit filters to reflect data structure hierarchy

### ISSUE THREAD

**Issue by aminahbl** [BuddhaNexus/buddhanexus#274]
Per discussion: https://discord.com/channels/1229483442203263056/1229483442677485589/1286351110839336960

> One more thing that is conceptionally giving me a headache at times: in our front end ui as well as parts of our data structures, we are treating collections as categories
While they are, conceptionally speaking, separate entities (just as files are not categories), so we have a hierarchy of three different entities: collections -> categories -> filenames

...

> We could also have just two dropdowns in the filter settings (as  opposed to now 4) that simply have the same structure as in the [language sidebar] menu. 

The refactor should also make sure that long filenames are displayed correctly (addressing issue first reported in BuddhaNexus/buddhanexus-frontend-next#138)

**Comment by ayya-vimala** [comment]
This seems to be working fine now.
