### ISSUE TITLE
Download Table & Numbers changes needed

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#276]
UPDATE below: https://github.com/BuddhaNexus/buddhanexus/issues/276#issuecomment-2483135830

After the backend merging of #245 the backend returns a BytesIO object for download. This breaks the frontend functionality so the frontend needs to be re-setup. See the docs for the correct output link.

Care should be taken that the  `download_data=''` parameter is set to `table` or `numbers` depending on which view is requested for download.

**Comment by ayya-vimala** [comment]
Most likely what is needed here is just to call the API without expecting a response. That should automatically download things to the user's downloads folder.
Add the additional output parameter to the curl like for instance `--output 'Downloads/buddhanexus-table.xlsx' \`. This can also include the actual filename and type of table requested (table or numbers). Something like this: `--output 'Downloads/buddhanexus_numbers_PA_dn_1.xlsx' \`

```
curl -X 'POST' \
  'http://dharmamitra.org:8001/api-db/download/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  --output 'Downloads/buddhanexus-table.xlsx' \
  -d '{
  "filename": "PA_dn_1",
  "filters": {
    "par_length": 30,
    "score": 30,
    "languages": [
      "all"
    ],
    "include_files": [
      "PA_dn_2"
    ]
  },
  "page": 0,
  "sort_method": "position",
  "folio": "",
  "download_data": "table"
}'```

**Comment by ayya-vimala** [comment]
Should be working now by just calling the API

**Comment by aminahbl** [comment]
https://discord.com/channels/1229483442203263056/1288619105292648488/1298562977976287243

**Comment by aminahbl** [comment]
Endpoint doesn't seem to be working ATM

**Comment by ayya-vimala** [comment]
This is weird. The endpoint works for me.

![image](https://github.com/user-attachments/assets/a8348b6a-67c7-49e5-9824-12b7a52b9769)

When I click Download it downloads the file "buddhanexus_download.xlsx"

**Comment by aminahbl** [comment]
Got to the bottom of this! I used the curl from your post in discord, but since then the backend address has changed. 🙃

**Comment by ayya-vimala** [comment]
Frontend part works for table view. Numbers view still needs to be reviewed at the backend. For now I close this.
