### ISSUE TITLE
Add pagination/search endpoint for menu

### ISSUE THREAD

**Issue by TrebuhD** [BuddhaNexus/buddhanexus#301]
The `https://buddhanexus2.kc-tbts.uni-hamburg.de/api/menus/${language}` endpoint currently responds with all data at once. We should add pagination there and support it in the frontend components, or ideally - use something like Algolia or ElasticSearch.

**Comment by sebastian-nehrdich** [comment]
this looks like an older legacy issue - we are just pushing the whole menudata at once in the current setup and I do believe this is OK given the fact that we need to reuse the data a lot on the frontend, right? Or are there still remaining performance concerns? Rendering this on the DB takes about 300ms per language, transmitting the data might take time too -- I am not sure if we need to change this to elasticsearch. Let me know what you think if performance is really an issue here. Caching and prerendering should also help.
