### ISSUE TITLE
Padding on match tag when many matches are found

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#314]
Only a very minor issue and don't spend too much time on this.
When more than 15000 matches are found, the match-field padding/margin changes and the text moves more to the top:

![Image](https://github.com/BuddhaNexus/buddhanexus/assets/49606945/80eaf804-85f2-4549-9be9-5110de830ce9)

**Comment by aminahbl** [comment]
After all the current PRs have been merged, you may want to double check if this is still an issue. I haven't directly looked at this, but while addressing various things in the vicinity, I also tried to improve the layout shift that was happening in connection with this element (both for the count number update and surrounding elements). It's still not 100% ideal, but this particular point may have been affected.

**Comment by ayya-vimala** [comment]
I can't see this any more.
