### ISSUE TITLE
Pull and align API model updates

### ISSUE THREAD

**Issue by aminahbl** [BuddhaNexus/buddhanexus#316]
Draft API updates have recently become available (see [discord](https://discord.com/channels/1229483442203263056/1229483442677485589/1292608568972804118) for details) and the frontend needs to be refactored to mirror these updates.

As part of this work the  migration from [use-query-params](https://www.npmjs.com/package/use-query-params#param-types:~:text=%3Fqp%3D123-,ObjectParam,-%7B%20key%3A%20string%20%7D) to [nuqs](https://nuqs.47ng.com/) should be completed (see [discord](https://discord.com/channels/1229483442203263056/1229483442677485589/1289244401066836040) for discussion).

### Related
- #274 
- https://github.com/BuddhaNexus/buddhanexus-frontend-next/pull/188

**Comment by ayya-vimala** [comment]
nuqs migration completed
