### ISSUE TITLE
Folios loaded as strings are not working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#328]
For instance for PA_an_1 folios are loaded as strings (therefore they are green):
![Image](https://github.com/user-attachments/assets/7ed9b215-8e22-4796-9398-564b516af5b3)

While for PA_dn_1 the folios are integers (and therefore red):
![Image](https://github.com/user-attachments/assets/82c97215-7b55-41c4-8192-6324f6b1d4a4)

For the first one, `PA_an_1` the folio selection works correctly, for `PA_dn_1` the query always returns `[]` when a folio number is selected.

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala please review, I fixed this today and reloaded the whole data.

**Comment by ayya-vimala** [comment]
Perfect! Thanks!
