### ISSUE TITLE
Files ending in $[0-9] are being loaded in the database

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#332]
Tibetan tiles ending in `$[0-9]` are being loaded in the database. This doesn't affect the general performance of the database and is not visible in the frontend. These files should not be loaded.

For instance `BO_K01_D0001-2_H0001-2$0`:

![Image](https://github.com/user-attachments/assets/33ba80ea-1cc0-49cc-aa10-928d8e5088bc)

**Comment by sebastian-nehrdich** [comment]
this is fixed now, please review.

**Comment by ayya-vimala** [comment]
Seems to be fixed now.
