### ISSUE TITLE
search include exclude filters not working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#356]
The search filter menu first shows the language and after selecting the language the include/exclude filters for that language become visible. However, when clicking on the dropdown box gives an error.

First step: select language:
![Image](https://github.com/user-attachments/assets/27f830d0-9fb9-4a4d-9bb4-d2b1a3c1e1a2)

Second step: select file, category or collection in include or exclude filter:
![Image](https://github.com/user-attachments/assets/bed4acf5-9532-4d8f-bb4e-18df0613467b)

Clicking on either include or exclude sources dropdown box the system crashes:
![Image](https://github.com/user-attachments/assets/f8c6ac68-75db-412d-9ce6-2ed72fe2ed90)

Expected behavior: menu should show in both include and exclude dropdowns as elsewhere:
![Image](https://github.com/user-attachments/assets/99db7721-36f5-483c-af24-44e362e91d43)

(and selected value passed to the backend)

**Comment by TrebuhD** [comment]
would be great if @aminahbl could have a look at this one

**Comment by aminahbl** [comment]
Per https://discord.com/channels/1229483442203263056/1229483707845312632/1318551901385785344, example search terms that work return results are needed for development.

**Comment by ayya-vimala** [comment]
Seem to work all fine now.
