### ISSUE TITLE
Text in searchfield unreadable in dark mode

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#365]
![Image](https://github.com/user-attachments/assets/146534af-597c-466f-908a-cbb5db527522)

The text and background are both white so it's not readable.

**Comment by aminahbl** [comment]
Included in PR #389

**Comment by ayya-vimala** [comment]
I'm not sure about this. In light mode it is like this:
![Image](https://github.com/user-attachments/assets/ef38f7b9-140d-40a8-a71d-c7640c9e6f6d)

In dark mode it looks like this:
![Image](https://github.com/user-attachments/assets/cd1d8f1a-c824-471e-999d-639439a1fb9d)

So still not readable, while the PR was merged.

**Comment by aminahbl** [comment]
Hmmmmm.... looks like the update wasn't pulled through (might have committed it on the wrong branch)... will check
