### ISSUE TITLE
Fix layout shift when setting filters

### ISSUE THREAD

**Issue by aminahbl** [BuddhaNexus/buddhanexus#375]
When filters are applied on a results page there is an unpleasant layout shift when the filter count chip is rendered

| initial view | view with chip |
|:---|---| 
| ![Image](https://github.com/user-attachments/assets/6baa8b3b-5138-4f80-bbd5-d23a19f8d27c) | ![Image](https://github.com/user-attachments/assets/5769355a-d696-4681-a8f6-4e39486f04b9) |

Example link: https://dharmamitra.org/nexus/db/pa/PA_dn_3/table

## steps to reproduce

- navigate to a text page in any view
- adjust filters

**Comment by aminahbl** [comment]
handled in #389-#391

**Comment by ayya-vimala** [comment]
I'm not entirely sure what I'm looking for here.

**Comment by aminahbl** [comment]
That's because it's fixed! :grin:

Previously the results panel was pushed up and down when filters were applied because a new "current filters" element was added on the block axis rather than inline axis.
