### ISSUE TITLE
DB source menu needs to display the textname instead of the filename

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus#385]
Once the backend /menudata/ returns a value called 'textname' this should be displayed instead of the filename in the menu.

**Comment by ayya-vimala** [comment]
@aminahbl  - the backend returns `textname` now as well so this can be changed. Issue #384 is solved.

**Comment by aminahbl** [comment]
Oh right, great, yes now I get you, thanks! It's the actual menu UI!

**Comment by aminahbl** [comment]
As this is a very small update that logically follows from the title update I've added this under #390

**Comment by ayya-vimala** [comment]
Looks good.
