### ISSUE TITLE
visual-view names contain confusing information for the users

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus#63]
This is not very urgent, but I noticed that the users might be confused by the 'technical information' such as 'R_K01[...]' in the labels of the sankey-graph. Its unfortunate because these labels need to be unique in the collections and if we just use RGYUD etc. we get the problem with the duplicates. Maybe it is possible to pull tricks via the  css formatting option for the data-nodes in the sankey. Unfortunately we cannot use HTML in the labels.

**Comment by ayya-vimala** [comment]
Yes, the uniqueness of the labels requires the L and R which is annoying. The L & R are also used to determine where the user has clicked.
Another way of doing it (and I can change that) is to us another symbol like f.i. "_" on one side and nothing on the other.

**Comment by ayya-vimala** [comment]
On a separate note: does the 1 overlap need to stay or should that go?
